version: '3.8'

services:
  task-db:
    image: postgres:alpine
    container_name: task-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-db
